- name: Shibboleth-IdP | find | privatekeys
  find:
    paths: /etc/pki/tls/private
    patterns: "{{ shibbolethidp_fqdn }}*.key"
  register: wildcard_files_to_delete

- name: Shibboleth-IdP | add | owner | privatekey
  acl:
    path: "{{ shibbolethidp_item.path }}"
    entity: jetty
    etype: user
    permissions: r
    state: present
  with_items: "{{ wildcard_files_to_delete.files }}"
  loop_control:
    loop_var: shibbolethidp_item
  notify: restart shibboleth-idp
