# - name: Configure Refeds MFA/SFA profile with static attribute values
# =====================================================================

- name: Refeds | MFA/SFA Profile | authn/general-authn.xml | authn/Password | Remove
  xml:
    xpath: "//beans:bean[@id='authn/Password']"
    ensure: "absent"
    file: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    namespaces:
      beans: http://www.springframework.org/schema/beans
      p: http://www.springframework.org/schema/p
  notify: restart shibboleth-idp

- name: Refeds | MFA/SFA Profile | authn/general-authn.xml | authn/Password | Add
  blockinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    marker: "        <!-- {mark} Ansible managed - auth/Password -->"
    insertbefore: "authn/Duo"
    content: |2
              <bean id="authn/Password" parent="shibboleth.AuthenticationFlow" p:passiveAuthenticationSupported="true" p:forcedAuthenticationSupported="true">
                <property name="supportedPrincipals">
                  <list>
                    <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="https://refeds.org/profile/sfa" />
                    <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" />
                    <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:Password" />
                  </list>
                </property>
              </bean>
  notify: restart shibboleth-idp

- name: Refeds | MFA/SFA Profile | authn/general-authn.xml | WeightMap | Remove
  xml:
    xpath: "//util:map[@id='shibboleth.AuthenticationPrincipalWeightMap']"
    ensure: "absent"
    file: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    namespaces:
      p: http://www.springframework.org/schema/p
      util: http://www.springframework.org/schema/util
  notify: restart shibboleth-idp

- name: Refeds | MFA/SFA Profile | authn/general-authn.xml | WeightMap | Add
  blockinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/authn/general-authn.xml"
    marker: "        <!-- {mark} Ansible managed - refeds mfa/sfa weightmap -->"
    insertbefore: "</beans>"
    content: |2
              <!--
              This is a map used to "weight" particular methods above others if the IdP has to randomly select one
              to insert into a SAML authentication statement. The typical use shown below is to bias the IdP in favor
              of expressing the SAML 2 PasswordProtectedTransport class over the more vanilla Password class on the
              assumption that the IdP doesn't accept passwords via an insecure channel. This map never causes the IdP
              to violate its matching rules if an RP requests a particular value; it only matters when nothing specific
              is chosen. Anything not in the map has a weight of zero.
              -->

             <util:map id="shibboleth.AuthenticationPrincipalWeightMap">
               <entry>
                 <key>
                   <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="https://refeds.org/profile/mfa" />
                 </key>
                 <value>3</value>
               </entry>
               <entry>
                 <key>
                   <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" />
                 </key>
                 <value>2</value>
               </entry>
               <entry>
                 <key>
                   <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="https://refeds.org/profile/sfa"/>
                 </key>
                 <value>1</value>
               </entry>
             </util:map>
  notify: restart shibboleth-idp

