- set_fact:
    haka_test_crt: "https://wiki.eduuni.fi/download/attachments/27297785/haka_testi_2015_sha2.crt?version=1&modificationDate=1430212953940&api=v2"

- get_url: url="{{ haka_test_crt }}" dest="{{ shibbolethidp_idp_home }}/credentials//haka_testi_2015_sha2.crt" mode=0755

- file: path={{ shibbolethidp_idp_home }}/metadata/backingFiles state=directory owner=jetty group=jetty recurse=yes mode=0750
 
- name: Add Haka-metadata provider (Haka-test)
  blockinfile:
    dest: "{{ shibbolethidp_idp_home }}/conf/metadata-providers.xml"
    marker: "<!-- {mark} ANSIBLE MANAGED HAKA-TEST -->"
    insertafter: "<!-- ========================================================================================== -->"
    content: |
      <MetadataProvider id="HTTPMetadata" xsi:type="FileBackedHTTPMetadataProvider" 
        refreshDelayFactor="0.125" maxRefreshDelay="PT2H" httpCaching="memory" 
        backingFile="%{idp.home}/metadata/backingFiles/haka-test-metadata.xml" 
        metadataURL="https://haka.funet.fi/metadata/haka_test_metadata_signed.xml">
        <MetadataFilter xsi:type="SignatureValidation" certificateFile="%{idp.home}/credentials/haka_testi_2015_sha2.crt" />
        <MetadataFilter xsi:type="EntityRoleWhiteList">
          <RetainedRole>md:SPSSODescriptor</RetainedRole>
        </MetadataFilter>
      </MetadataProvider>
