---
# tasks file for CSCfi.shibboleth-idp/shibbolethidp_mfa-server
- set_fact:
    stepup_version: "{{ shibbolethidp_stepupversion }}"
    stepup_src: "/tmp/stepup-proxy"

- set_fact:
    stepup_version: "{{ shibbolethidp_stepupversion }}"
    mpassid_version: "{{ shibbolethidp_mpassidversion }}"
    mpassid_release: "{{ shibbolethidp_mpassidrelease }}"
    mpassid_src: "/tmp/MPASSid-proxy"
    stepup_jars:
      - 'idp-ssointerceptor-impl-stepup/target/idp-ssointerceptor-impl-stepup-{{ stepup_version }}.jar'
      - 'idp-ssointerceptor-api-stepup/target/idp-ssointerceptor-api-stepup-{{ stepup_version }}.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/HikariCP-*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/commons-collections*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/commons-lang*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/googleauth-*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/json-smart-*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/lang-tag-*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/nimbus-jose-jwt-*'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/oauth2-oidc-sdk-*.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/spring-security-crypto-*.RELEASE.jar'
      - 'idp-ssointerceptor-impl-stepup/target/dependency/twilio-*.jar'

- name: IDP | MFA-SERVER | INITIAL PACKAGES | npm, maven
  yum: name={{ item_mfa }} state=present
  with_items:
    - git
    - maven
  loop_control:
    loop_var: item_mfa

- name: IDP | MFA-SERVER | MPASSid | Download | git | MPASSid-proxy {{ mpassid_version }}
  git:
    repo: 'https://github.com/mpassid/MPASSid-proxy'
    dest: "{{ mpassid_src }}"
    version: "{{ mpassid_version }}"
    
- name: IDP | MFA-SERVER | MPASSid | Compile | MPASSid-proxy
  shell: mvn -f pom.xml clean install -DskipTests=true #mvn package
  args:
    chdir: "{{ mpassid_src }}"
    executable: /bin/bash
    creates: /tmp/MPASSid-proxy/idp-authn-impl-shibsp/target/checkstyle-checker.xml

- name: IDP | MFA-SERVER | MPASSid | ShipSP | jars
  copy: src={{ item_stepup.src }} dest={{ item_stepup.dest }} owner=root group=jetty mode=0750 force=no remote_src=yes
  with_items:
    - { src: "{{ mpassid_src }}/idp-authn-impl-shibsp/target/idp-authn-impl-shibsp-{{ mpassid_release }}.jar", dest: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/" }
    - { src: "{{ mpassid_src }}/idp-authn-api-shibsp/target/idp-authn-api-shibsp-{{ mpassid_release }}.jar", dest: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/" }
    - { src: "{{ mpassid_src }}/idp-authn-impl-shibsp/target/idp-authn-impl-shibsp-{{ mpassid_release }}-bin/idp-authn-impl-shibsp-{{ mpassid_release }}/conf/shib-authn-config.xml", dest: "{{ shibbolethidp_idp_home }}/conf/authn/" }
  loop_control:
    loop_var: item_stepup
  notify: rebuild shibboleth-idp

- name: IDP | MFA-SERVER | MPASSid | ShipSP | add | flows
  shell: cp -r "{{ mpassid_src }}/idp-authn-impl-shibsp/target/idp-authn-impl-shibsp-{{ mpassid_release }}-bin/idp-authn-impl-shibsp-{{ mpassid_release }}/flows/" {{ shibbolethidp_idp_home }}/.

- name: IDP | MFA-SERVER | MPASSid | ShipSP | remove | existing flow
  file:
    state: absent
    path: "{{ shibbolethidp_idp_home }}/flows/authn/ShibSP"
  notify: restart shibboleth-idp

- name: IDP | MFA-SERVER | MPASSid | ShibSP | rename
  command: mv "{{ shibbolethidp_idp_home }}/{{ item_stepup.src }}" "{{ shibbolethidp_idp_home }}/{{ item_stepup.dest }}"
  with_items:
    - { src: "flows/authn/ShibExample", dest: "flows/authn/ShibSP" }
    - { src: "flows/authn/ShibSP/shibexample-flow.xml", dest: "flows/authn/ShibSP/shibsp-flow.xml" }
  loop_control:
    loop_var: item_stepup
  notify: restart shibboleth-idp

### General MFA section

- name: IDP | MFA-SERVER | StepUP | Delete | httpc*.jar
  shell: "rm {{ shibbolethidp_idp_home }}/webapp/WEB-INF/lib/httpc*.jar"
  notify: rebuild shibboleth-idp

- name: IDP | MFA-SERVER | StepUP | Download | httpcore, httpdclient-cache, httpclient
  get_url: url="{{ item_stepup.src }}" dest="{{ item_stepup.dest }}" mode=0644
  with_items:
    - { src: "http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar", dest: "{{ shibbolethidp_idp_home }}/webapp/WEB-INF/lib/" }
    - { src: "http://central.maven.org/maven2/org/apache/httpcomponents/httpclient-cache/4.5.3/httpclient-cache-4.5.3.jar", dest: "{{ shibbolethidp_idp_home }}/webapp/WEB-INF/lib/" }
    - { src: "http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar", dest: "{{ shibbolethidp_idp_home }}/webapp/WEB-INF/lib/" }
  loop_control:
    loop_var: item_stepup
  notify: rebuild shibboleth-idp
