---
### STEPUP PROXY Section

- name: IDP | MFA-SERVER | StepUP | Download | git | {{ stepup_src }}
  git:
    repo: 'https://github.com/CSCfi/stepup-proxy'
    dest: "{{ stepup_src }}"
    version: stepup-v{{ stepup_version }}
  when: stepup_version != 'master'

- name: IDP | MFA-SERVER | StepUP | Download | git | {{ stepup_src }}
  git:
    repo: 'https://github.com/CSCfi/stepup-proxy'
    dest: "{{ stepup_src }}"
  when: stepup_version == 'master'
                      
- name: IDP | MFA-SERVER | StepUP | Compile | {{ stepup_src }}
  shell: mvn -f pom.xml clean package #mvn package
  args:
    chdir: "{{ stepup_src }}"
    executable: /bin/bash
    creates: /tmp/stepup-proxy/idp-ssointerceptor-impl-stepup/target/checkstyle-checker.xml
  become: yes

- name: IDP | MFA-SERVER | StepUP | Create | Directories (flows/views)
  file: path="{{ shibbolethidp_idp_home }}/{{ item_stepup.src }}/" state=directory
  with_items:
    - { src: "flows/oidc/mfarequest" }
    - { src: "flows/authn/mfa" }
    - { src: "flows/intercept/stepup" }
    - { src: "views/authn" }
    - { src: "views/oidc" }
  loop_control:
    loop_var: item_stepup

- name: Copy stepup flows, overwriting existing ones
  copy: src="{{ item_stepup.src }}" dest="{{ item_stepup.dest }}" owner=root group=root mode=0644 remote_src=yes
  with_items:
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/oidc/mfarequest/mfarequest-flow.xml", dest: "{{ shibbolethidp_idp_home }}/flows/oidc/mfarequest/mfarequest-flow.xml" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/authn/mfa/mfa-flow.xml", dest: "{{ shibbolethidp_idp_home }}/flows/authn/mfa/mfa-flow.xml" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/intercept/stepup/stepup-flow.xml", dest: "{{ shibbolethidp_idp_home }}/flows/intercept/stepup/stepup-flow.xml" }
  loop_control:
    loop_var: item_stepup

- name: Copy stepup beans, preserving existing ones
  copy: src="{{ item_stepup.src }}" dest="{{ item_stepup.dest }}" owner=root group=root mode=0644 remote_src=yes force=no
  with_items:
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/oidc/mfarequest/mfarequest-beans.xml", dest: "{{ shibbolethidp_idp_home }}/flows/oidc/mfarequest/mfarequest-beans.xml" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/authn/mfa/mfa-beans.xml", dest: "{{ shibbolethidp_idp_home }}/flows/authn/mfa/mfa-beans.xml" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/intercept/stepup/stepup-beans.xml", dest: "{{ shibbolethidp_idp_home }}/flows/intercept/stepup/stepup-beans.xml" }
  loop_control:
    loop_var: item_stepup

- name: Copy stepup beans as exmple beans, overwriting existing ones
  copy: src="{{ item_stepup.src }}" dest="{{ item_stepup.dest }}" owner=root group=root mode=0644 remote_src=yes
  with_items:
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/oidc/mfarequest/mfarequest-beans.xml", dest: "{{ shibbolethidp_idp_home }}/flows/oidc/mfarequest/mfarequest-beans.xml.example" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/authn/mfa/mfa-beans.xml", dest: "{{ shibbolethidp_idp_home }}/flows/authn/mfa/mfa-beans.xml.example" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/flows/intercept/stepup/stepup-beans.xml", dest: "{{ shibbolethidp_idp_home }}/flows/intercept/stepup/stepup-beans.xml.example" }
  loop_control:
    loop_var: item_stepup

- name: Copy stepup views, overwriting existing ones
  copy: src="{{ item_stepup.src }}" dest="{{ item_stepup.dest }}" owner=root group=root mode=0644 remote_src=yes
  with_items:
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/oidc/mfarequest-error.vm", dest: "{{ shibbolethidp_idp_home }}/views/oidc/mfarequest-error.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-backend-progress.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-backend-progress.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-backend.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-backend.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-condolences.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-condolences.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-managesimple.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-managesimple.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-manage.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-manage.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-performed.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-performed.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-register.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-register.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-startregister.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-startregister.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-wrongresponse.vm", dest: "{{ shibbolethidp_idp_home }}/views/authn/mfa-wrongresponse.vm" }
    - { src: "{{ stepup_src }}/idp-ssointerceptor-impl-stepup/src/main/resources/views/intercept/stepup-error.vm", dest: "{{ shibbolethidp_idp_home }}/views/intercept/stepup-error.vm" }
  loop_control:
    loop_var: item_stepup

- name: IDP | MFA-SERVER | StepUP | Delete | jars
  shell: rm {{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/{{ item_stepup | basename }}
  ignore_errors: yes
  with_items:
    - "{{ stepup_jars }}"
  loop_control:
    loop_var: item_stepup
  notify: rebuild shibboleth-idp


- name: IDP | MFA-SERVER | StepUP | Copy | jars
  shell: cp {{ stepup_src }}/{{ item_stepup }} {{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib/.
  with_items:
    - "{{ stepup_jars }}"
  loop_control:
    loop_var: item_stepup
  notify: rebuild shibboleth-idp
