---
# handlers file for shibboleth-idp
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart shibboleth-idp
  service: name=shibboleth-idp state=restarted

- name: rebuild shibboleth-idp
  shell: "source /etc/default/shibboleth-idp && {{ shibbolethidp_idp_home }}/bin/build.sh"
  args:
    executable: /bin/bash
  notify: restart shibboleth-idp




