- name: Configure | OIDC | Download | Plugin | OIDC Common
  shell: "source /etc/default/shibboleth-idp && {{ shibbolethidp_idp_home }}/bin/plugin.sh -i https://shibboleth.net/downloads/identity-provider/plugins/oidc-common/{{ shibbolethidp_oidccommonplugin_version }}/oidc-common-dist-{{ shibbolethidp_oidccommonplugin_version }}.tar.gz"
  args:
    executable: /bin/bash
  when: (inventory_hostname != 'localhost')

- name: Configure | OIDC | Download | Plugin | OIDC OP
  shell: "source /etc/default/shibboleth-idp && {{ shibbolethidp_idp_home }}/bin/plugin.sh -i https://shibboleth.net/downloads/identity-provider/plugins/oidc-op/{{ shibbolethidp_oidcplugin_version }}/idp-plugin-oidc-op-distribution-{{ shibbolethidp_oidcplugin_version }}.tar.gz"
  args:
    executable: /bin/bash
  when: (inventory_hostname != 'localhost')

  notify: reown shibboleth-idp

- name: Configure | {{ item }} | Detect | Duplicate | Plugins
  find:
    paths: "{{ shibbolethidp_idp_home }}/edit-webapp/WEB-INF/lib"
    patterns: "^(?!.*({{ shibbolethidp_oidcplugin_version | regex_replace('[^0-9.]', '') }})).*oidc-extension"
    use_regex: true
  register: files_to_delete

- name: Configure | {{ oidc }} | Delete | Older | Plugins
  file:
    path: "{{ shibbolethidp_item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  loop_control:
    loop_var: shibbolethidp_item

- name: Configure | {{ item }} | Configure | oidc.properties
  lineinfile: dest={{ shibbolethidp_idp_home }}/conf/oidc.properties regexp="^#?\s*({{ item_oidc.option }}\s*=)" backrefs=yes line="\\1 {{ item_oidc.value }}"
  with_items:
    - { option: 'idp.oidc.issuer', value: "https://{{ shibbolethidp_fqdn }}", state: present }
  loop_control:
    loop_var: item_oidc

#- name: Configurable | OIDC | Import OIDC extension configuration files
# =======================================================================

- name: Configure | {{ item }} | Del | oidc import files
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/{{ oidcitem.file}}"
    xpath: /x:beans/x:import[@resource="{{ oidcitem.import }}"]
    namespaces:
      x: "http://www.springframework.org/schema/beans"
    state: absent
  loop_control:
    loop_var: oidcitem
  with_items:
    - { import: oidc-credentials.xml, file: credentials.xml, path: empty }
    - { import: oidc-claim-rules.xml, file: attributes/default-rules.xml, path: empty }

- name: Configure | {{ item }} | Add | oidc import files"
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/{{ oidcitem.file }}"
    xpath: "{{ oidcitem.path }}"
    pretty_print: yes
    insertbefore: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      util: "http://www.springframework.org/schema/util"
    add_children:
      - import:
          resource: "{{ oidcitem.import }}"
  loop_control:
    loop_var: oidcitem
  with_items:
    - { import: oidc-credentials.xml, file: credentials.xml, path: "/x:beans/util:list" }
    - { import: oidc-claim-rules.xml, file: attributes/default-rules.xml, path: "/x:beans/util:list" }

- name: Configure | {{ item }} | Create | Directory | .well-known | NOTE MISSING STILL That file 
  file: path={{ shibbolethidp_wwwroot }}/.well-known state=directory

- name: Configure | OIDC | Credentials 
  shell: source /etc/default/shibboleth-idp && {{ shibbolethidp_idp_home }}/bin/{{ oidcitem }}
  args:
    chdir: "{{ shibbolethidp_idp_home }}"
    executable: /bin/bash
  with_items:
   - "jwtgen.sh -t RSA -s 2048 -u sig -i defaultRSASign | tail -n +2 > credentials/idp-signing-rs.jwk"
   - "jwtgen.sh -t EC -c P-256 -u sig -i defaultECSign | tail -n +2 > credentials/idp-signing-es.jwk"
   - "jwtgen.sh -t RSA -s 2048 -u enc -i defaultRSAEnc | tail -n +2 > credentials/idp-encryption-rsa.jwk"
  loop_control:
    loop_var: oidcitem
  when: (inventory_hostname != 'localhost')

- name: Configurable | {{ item }} | Del | ProfileConfigurations < conf/relying-party.xml
  xml:
    xpath: "{{ oidcitem }}"
    ensure: "absent"
    file: "{{ shibbolethidp_idp_home }}/conf/relying-party.xml"
    namespaces:
      x: http://www.springframework.org/schema/beans
  loop_control:
    loop_var: oidcitem
  with_items:
    - '/x:beans/x:bean[@id="shibboleth.UnverifiedRelyingParty"]'
    - '/x:beans/x:bean[@id="shibboleth.DefaultRelyingParty"]/x:property[@name="profileConfigurations"]/x:list/x:bean[@parent="OIDC.SSO"]'
    - '/x:beans/x:bean[@id="shibboleth.DefaultRelyingParty"]/x:property[@name="profileConfigurations"]/x:list/x:bean[@parent="OIDC.UserInfo"]'
    - '/x:beans/x:bean[@id="shibboleth.DefaultRelyingParty"]/x:property[@name="profileConfigurations"]/x:list/x:bean[@parent="OAUTH2.Revocation"]'
  notify: restart shibboleth-idp

- name: Configure | {{ item }} | Add | ProfileConfigurations > conf/relying-party.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/relying-party.xml"
    xpath: /x:beans/x:bean[@id="shibboleth.DefaultRelyingParty"]/x:property[@name="profileConfigurations"]/x:list/x:ref[@bean="Liberty.SSOS"]
    pretty_print: yes
    insertafter: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      util: "http://www.springframework.org/schema/util"
      p: "http://www.springframework.org/schema/p"
      c: "http://www.springframework.org/schema/c"
    add_children:
      - bean:
          parent: "OIDC.SSO"
          "{http://www.springframework.org/schema/p}postAuthenticationFlows": "attribute-release"
      - bean:
          parent: "OIDC.UserInfo"
      - bean:
          parent: "OAUTH2.Revocation"

- name: Configure | {{ item }} | Add | ProfileConfigurations > conf/relying-party.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/relying-party.xml"
    xpath: /x:beans/x:bean[@id="shibboleth.DefaultRelyingParty"]
    pretty_print: yes
    insertbefore: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      util: "http://www.springframework.org/schema/util"
      p: "http://www.springframework.org/schema/p"
      c: "http://www.springframework.org/schema/c"
    add_children:
      - bean:
          id: shibboleth.UnverifiedRelyingParty
          parent: RelyingParty
          _:
             - property:
                 name: profileConfigurations
                 _:
                    - list:
                         _:
                            - ref:
                                bean: OIDC.Keyset

- name: Configure | {{ item }} | Del | AttributeDefinition & DataConnector] < conf/attribute-resolver.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/attribute-resolver.xml"
    xpath: "{{ oidcitem }}"
    namespaces:
      x: "urn:mace:shibboleth:2.0:resolver"
    state: absent
  loop_control:
    loop_var: oidcitem
  with_items:
    - '/x:AttributeResolver/x:AttributeDefinition[@id="subject"]'
    - '/x:AttributeResolver/x:DataConnector[@id="computedSubjectId"]'

- name: Configure | {{ item }} | Add | AttributeDefinition[@id="subject"] > conf/attribute-resolver.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/attribute-resolver.xml"
    xpath: /x:AttributeResolver/x:AttributeDefinition
    pretty_print: yes
    insertbefore: yes
    namespaces: &namespaces
      x: "urn:mace:shibboleth:2.0:resolver"
      xsi: "http://www.w3.org/2001/XMLSchema-instance"
    add_children:
      - AttributeDefinition:
          id: subject
          "{http://www.w3.org/2001/XMLSchema-instance}type": Simple
          activationConditionRef: SubjectRequired
          _:
            - InputDataConnector:
                ref: computedSubjectId
                attributeNames: subjectId
            - AttributeEncoder:
                "{http://www.w3.org/2001/XMLSchema-instance}type": "oidcext:OIDCString"
                name: sub

- name: Configure | {{ item }} | Add | DataConnector[@id="computedSubjectId"] > conf/attribute-resolver.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/attribute-resolver.xml"
    xpath: /x:AttributeResolver/x:DataConnector
    pretty_print: yes
    insertafter: yes
    namespaces:
      x: "urn:mace:shibboleth:2.0:resolver"
      xsi: "http://www.w3.org/2001/XMLSchema-instance"
    add_children:
      - DataConnector:
          id: computedSubjectId
          "{http://www.w3.org/2001/XMLSchema-instance}type": ComputedId
          generatedAttributeID: "subjectId"
          salt: "%{idp.oidc.subject.salt}"
          algorithm: "%{idp.oidc.subject.algorithm:SHA}"
          encoding: "%{idp.oidc.subject.encoding:BASE32}"
          _:
            - InputAttributeDefinition:
                ref: "%{idp.oidc.subject.sourceAttribute}"

- name: Configure | {{ item }} | Del | AttributeFilterPolicy[@id="OPENID_SCOPE"] < conf/attribute-filter.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/attribute-filter.xml"
    xpath: /x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id="OPENID_SCOPE"]
    state: absent
    namespaces:
      x: "urn:mace:shibboleth:2.0:afp"

- name: Configure | {{ item }} | Add | AttributeFilterPolicy[@id="OPENID_SCOPE"] > conf/attribute-filter.xml
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/attribute-filter.xml"
    xpath: /x:AttributeFilterPolicyGroup
    pretty_print: yes
    namespaces:
      x: "urn:mace:shibboleth:2.0:afp"
      xsi: "http://www.w3.org/2001/XMLSchema-instance"
    add_children:
      - AttributeFilterPolicy:
          id: "OPENID_SCOPE"
          _:
            - PolicyRequirementRule:
                value: "openid"
                "{http://www.w3.org/2001/XMLSchema-instance}type": "oidcext:OIDCScope"
            - AttributeRule:
                attributeID: subject
                _:
                  - PermitValueRule:
                      "{http://www.w3.org/2001/XMLSchema-instance}type": "ANY"

- name: Configure | {{ item }} | Del | oidcFileResolvers
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/oidc-clientinfo-resolvers.xml"
    xpath: "{{ oidcitem }}"
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      util: "http://www.springframework.org/schema/util"
    state: absent
  loop_control:
    loop_var: oidcitem
  with_items:
    - '/x:beans/util:list[@id="shibboleth.oidc.ClientInformationResolvers"]/x:ref[@bean="oidcFileResolver"]'
    - '/x:beans/x:bean[@id="oidcFileResolver"]'

- name: Configure | {{ item }} | Add | oidcFileResolver | reference
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/oidc-clientinfo-resolvers.xml"
    xpath: /x:beans/util:list[@id="shibboleth.oidc.ClientInformationResolvers"]
    pretty_print: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      util: "http://www.springframework.org/schema/util"
    add_children:
      - ref:
          bean: "oidcFileResolver"

- name: Configure | {{ item }} | Add | oidcFileResolver
  xml:
    file: "{{ shibbolethidp_idp_home }}/conf/oidc-clientinfo-resolvers.xml"
    xpath: /x:beans
    pretty_print: yes
    namespaces:
      x: "http://www.springframework.org/schema/beans"
      util: "http://www.springframework.org/schema/util"
      p: "http://www.springframework.org/schema/p"
      c: "http://www.springframework.org/schema/c"
    add_children:
      - bean:
          id: "oidcFileResolver"
          parent: "shibboleth.oidc.FilesystemClientInformationResolver"
          "{http://www.springframework.org/schema/c}metadata": "%{idp.home}/metadata/oidc-client.json"
